TEMPLATE = subdirs
SUBDIRS += ptk_repair_wkt ptk_wkt_to_ply ptk_gridify_wkt ptk_quadify_wkt ptk_simplify_wkt ptk_xform_wkt ptk_wkt_to_ctm
ptk_repair_wkt.file = ptk_repair_wkt.pro
ptk_wkt_to_ply.file = ptk_wkt_to_ply.pro
ptk_gridify_wkt.file = ptk_gridify_wkt.pro
ptk_quadify_wkt.file = ptk_quadify_wkt.pro
ptk_simplify_wkt.file = ptk_simplify_wkt.pro
ptk_xform_wkt.file = ptk_xform_wkt.pro
ptk_wkt_to_ctm.file = ptk_wkt_to_ctm.pro
